import { mkdtemp, unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildApp } from '../../src/api/server.js';
import { buildServices } from '../../src/core/services.js';

describe('recording HTTP range playback', () => {
  it('opens only the completed recording file through the existing open endpoint, retaining default directory behavior', async () => {
    const services = buildServices({ dbPath: ':memory:' });
    const room = services.rooms.create({ platform: 'bilibili', url: 'https://live.bilibili.com/123', displayName: 'external playback' });
    const dir = await mkdtemp(path.join(tmpdir(), 'lr-open-video-'));
    const file = path.join(dir, '录像 & 中文 空格.mp4');
    await writeFile(file, Buffer.from('fixture'));
    const recording = services.recordings.create({ roomId: room.id, roomName: room.displayName, platform: room.platform, streamSessionId: null, streamTitle: '录像' });
    services.recordings.update(recording.id, { state: 'completed', filePath: file });
    const { app } = buildApp(services);
    const base = { method: 'POST' as const, url: `/api/v1/recordings/${recording.id}/open`, headers: { host: '127.0.0.1:43120' } };
    const play = { ...base, url: `/api/v1/recordings/${recording.id}/play` };
    expect((await app.inject(play)).statusCode).toBe(200);
    expect((await app.inject({ ...base, payload: { target: 'file' } })).statusCode).toBe(200);
    expect((await app.inject(base)).statusCode).toBe(200);
    expect((await app.inject({ ...base, payload: { target: '/arbitrary/path' } })).statusCode).toBeGreaterThanOrEqual(400);
    services.recordings.update(recording.id, { state: 'processing' });
    expect((await app.inject(play)).statusCode).toBeGreaterThanOrEqual(400);
    expect((await app.inject({ ...base, payload: { target: 'file' } })).statusCode).toBeGreaterThanOrEqual(400);
    services.recordings.update(recording.id, { state: 'completed', filePath: dir });
    expect((await app.inject({ ...base, payload: { target: 'file' } })).statusCode).toBe(404);
    services.recordings.update(recording.id, { filePath: file });
    await unlink(file);
    expect((await app.inject(play)).statusCode).toBe(404);
    expect((await app.inject({ ...base, payload: { target: 'file' } })).statusCode).toBe(404);
    await app.close();
  });

  it('supports single, open-ended and suffix ranges while retaining full reads', async () => {
    const services = buildServices({ dbPath: ':memory:' });
    const room = services.rooms.create({ platform: 'bilibili', url: 'https://live.bilibili.com/123', displayName: 'range' });
    const file = path.join(await mkdtemp(path.join(tmpdir(), 'lr-range-')), 'recording.flv');
    const data = Buffer.concat([Buffer.from('FLV'), Buffer.from('0123456789')]);
    await writeFile(file, data);
    const recording = services.recordings.create({ roomId: room.id, roomName: room.displayName, platform: room.platform, streamSessionId: null, streamTitle: '' });
    services.recordings.update(recording.id, { state: 'completed', filePath: file });
    const { app } = buildApp(services);
    const base = { method: 'GET' as const, url: `/api/v1/recordings/${recording.id}/file`, headers: { host: '127.0.0.1:43120' } };
    const full = await app.inject(base);
    expect(full.statusCode).toBe(200);
    expect(full.headers['content-length']).toBe(String(data.length));
    const partial = await app.inject({ ...base, headers: { ...base.headers, range: 'bytes=3-5' } });
    expect(partial.statusCode).toBe(206);
    expect(partial.headers['content-range']).toBe(`bytes 3-5/${data.length}`);
    expect(partial.rawPayload.toString()).toBe('012');
    const suffix = await app.inject({ ...base, headers: { ...base.headers, range: 'bytes=-2' } });
    expect(suffix.statusCode).toBe(206);
    expect(suffix.rawPayload.toString()).toBe('89');
    const invalid = await app.inject({ ...base, headers: { ...base.headers, range: 'bytes=999-' } });
    expect(invalid.statusCode).toBe(416);
    expect(invalid.headers['content-range']).toBe(`bytes */${data.length}`);
    const multiple = await app.inject({ ...base, headers: { ...base.headers, range: 'bytes=0-1,3-4' } });
    expect(multiple.statusCode).toBe(200);
    expect(multiple.rawPayload).toEqual(data);
    const head = await app.inject({ ...base, method: 'HEAD' });
    expect(head.statusCode).toBe(200);
    expect(head.headers['content-length']).toBe(String(data.length));
    expect(head.rawPayload.length).toBe(0);
    await unlink(file);
    const missing = await app.inject({ ...base, method: 'HEAD' });
    expect(missing.statusCode).toBe(404);
    expect(missing.rawPayload.length).toBe(0);
    await app.close();
  });
});
